### ISSUE TITLE
Custom Laravel Cache Implementation Help

### ISSUE THREAD

**Issue by springfirenator** [fhteam/laravel-cache-redis-extended#1]
Hello, I'm working on a project where I need to keep an account of users online in real time. I see redis a good fit for storing and expiring sessions automatically. However, I run into a problem, see this code:

```
// Mark each user as online for 15 minutes separately
Cache::tags('usersonline')->put('user', "John Afolabi", 15);
Cache::tags('usersonline')->put('user', "Thomas", 15);
Cache::tags('usersonline')->put('user', "Alexandar", 15);

// Get online users
var_dump(Cache::tags('usersonline')->get('users'));
```

By default, this returns just `Alexander` i.e., last updated value. Can you tell me whats the best way to get all the usernames?

**Comment by FractalizeR** [comment]
I am not sure you can make it work like this. Laravel uses tags to derive key names. He doesn't make any collections ([hashes](http://redis.io/commands#hash)). So you cannot just get all keys, that were tagged with the specific key. 

If you really want to use Redis to store sessions, it would be complicated since you cannot expire a member of a hash by itself. Plus you have no callbacks telling you some specific key is expired (to clear it out of your collection / hash).

I think you may resort to using database table for storing sessions. It would be so much easier.
